---
:verbose: false
:concurrency: 1

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", "1") %>
